apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: catalog-build
spec:
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: "http://gogs-lab-infra.devapps-8e59.generic.opentlc.com/student/cd-infra.git"
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: NEXUS_URL
          value: "http://nexus.lab-infra.svc:8081"
        - name: DEV_PROJECT
          value: "dev"
      jenkinsfilePath: Jenkinsfile.catalog-build
    type: JenkinsPipeline
  triggers:
    - github:
        secret: CqPGlXcKJXXqKxW4Ye6z
      type: GitHub
    - generic:
        secret: 4LXwMdx9vhQY4WXbLcFR
      type: Generic
    - type: ConfigChange
